import { offset, availableVersion,
  moduleBaseAddress,
  moduleLoad,
  currentVersion as currentversion,
  nodeList,
  contactList,
  chatroomNodeList,
  chatroomMemberList,
  loggedIn as loggedin } from '../../module/CommonData'//"..//CommonData";
import { readString,   readWideString,
  readWStringPtr,
  readStringPtr,
  agentReadyCallback ,
  getTestInfoFunction,
  isLoggedInFunction } from "../../module/CommonFn";
import { getHeaderNodeAddress,  getChatroomNodeAddress,
  getBaseNodeAddress } from "../../module/getAddressData";
import { checkSupportedFunction,getChatroomMemberInfoFunction,
  nickRoomId ,
  nickMemberId,
  nickStructPtr,
  nickBuff ,
  memberNickBuffAsm ,
  nickRetAddr,
  getChatroomMemberNickInfoFunction,
  getContactNativeFunction,
  getWechatVersionFunction,
  getWechatVersionStringFunction } from "../../module/getData";
import { getMyselfInfoFunction,getMyselfIdFunction } from "../../module/getUserData";
import { msgStruct, msgstrPtr,
  initmsgStruct,
  retidStruct ,
  retidPtr,
  initidStruct,
  retPtr,
  retStruct,
  initStruct,
  atStruct,
  initAtMsgStruct } from "../../module/initStruct";
import { recvMsgNativeCallback,asmAtMsg ,
  roomid_,
  msg_,
  wxid_,
  atid_,
  ecxBuffer,
  sendAtMsgNativeFunction,
  attatchWxid,
  attatchPath,
  attatchPathPtr,
  attatchAsm,
  attatchBuf,
  attatchEbp,
  attatchEaxbuf,
  sendAttatchMsgNativeFunction,
  SendMiniProgramNativeFunction,
  sendMsgNativeFunction,
  buffwxid,
  imagefilepath,
  pathPtr,
  picWxid,
  picWxidPtr,
  picAsm,
  picbuff,
  sendPicMsgNativeFunction } from "../../module/Message_about";
import { chatroomRecurse,recurse } from "../../module/parse-getData";
import { callLoginQrcodeFunction, checkQRLoginNativeCallback,
  getQrcodeLoginData } from "../../module/QR-aboutFn";
import { hookLoginEventCallback,hookLogoutEventCallback } from "../../module/version-hook";

let currentVersion = currentversion.date
let loggedIn = loggedin.date

export {
  loggedIn,
  currentVersion,
  offset, availableVersion,
  moduleBaseAddress,
  moduleLoad,
  currentVersion as currentversion,
  nodeList,
  contactList,
  chatroomNodeList,
  chatroomMemberList,
  readString,   readWideString,
  readWStringPtr,
  readStringPtr,
  agentReadyCallback ,
  getTestInfoFunction,
  isLoggedInFunction,
  getHeaderNodeAddress,  getChatroomNodeAddress,
  getBaseNodeAddress,
  checkSupportedFunction,getChatroomMemberInfoFunction,
  nickRoomId ,
  nickMemberId,
  nickStructPtr,
  nickBuff ,
  memberNickBuffAsm ,
  nickRetAddr,
  getChatroomMemberNickInfoFunction,
  getContactNativeFunction,
  getWechatVersionFunction,
  getWechatVersionStringFunction,
  getMyselfInfoFunction,getMyselfIdFunction,
  msgStruct, msgstrPtr,
  initmsgStruct,
  retidStruct ,
  retidPtr,
  initidStruct,
  retPtr,
  retStruct,
  initStruct,
  atStruct,
  initAtMsgStruct,
  recvMsgNativeCallback,asmAtMsg ,
  roomid_,
  msg_,
  wxid_,
  atid_,
  ecxBuffer,
  sendAtMsgNativeFunction,
  attatchWxid,
  attatchPath,
  attatchPathPtr,
  attatchAsm,
  attatchBuf,
  attatchEbp,
  attatchEaxbuf,
  sendAttatchMsgNativeFunction,
  SendMiniProgramNativeFunction,
  sendMsgNativeFunction,
  buffwxid,
  imagefilepath,
  pathPtr,
  picWxid,
  picWxidPtr,
  picAsm,
  picbuff,
  sendPicMsgNativeFunction,
  chatroomRecurse,recurse ,
  callLoginQrcodeFunction, checkQRLoginNativeCallback,
  getQrcodeLoginData,
  hookLoginEventCallback,hookLogoutEventCallback

}
